# -*- coding: utf-8 -*-
"""Desafio-Womakerscode-TechMinas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XsSgs60onBQf2AmWrGriLN__E59ESkcs

### Bem vindas ao desafio de python do bootcamp Tech Minas da WoMakersCode!
Neste notebook, voce deve escrever o codigo python em resposta à cada uma das perguntas. Esteja atenta ao enunciado do problema!

### Desafio 1
Escreva uma função em python que lê dois números inteiros (a,b) e gere como resultado as seguintes operações:adição, subtração, multiplicação e divisão. Execute a funçao na celula abaixo, deixando visivel exemplos de resultados.
"""

##### ESCREVER A FUNÇAO ABAIXO
def operations(a,b):
  #### Escrever abaixo
    soma = a + b
    sub = a- b
    mult = a * b
    div = a / b

    return soma, sub, mult, div

#### RODAR A FUNÇAO
a = int(input('Digite o primeiro número inteiro: '))
b = int(input('Digite o segundo número inteiro: '))
print(f'Os valores da soma, subtração, multiplicação e divisão de a e b, respectivamente, são: {operations(a,b)}')

"""### Desafio 2
Escreva uma função em python que leia como input uma idade e retorne a classificaçao da idade do individuo da seguinte forma em:

*  Criança – 0 a 12 anos
*  Adolescente – 13 a 17 anos
*  Adulto – acima de 18 anos


Se a idade for um número negativo, mostrar a mensagem que a "idade inválida"


"""

##### ESCREVER A FUNCAO ABAIXO
def classifica_idade(idade):
  #### escrever abaixo
    if 0 <= idade <= 12:
      print('Você é uma criança!')
    elif 13 <= idade <= 17:
      print('Você é um adolescente!')
    elif 18 < idade:
      print('Você é um adulto!')
    else:
      print('\033[1;31mIdade inválida!\033[m')

#### RODAR A FUNCAO
idade = int(input('Qual a sua idade? '))
classifica_idade(idade)

"""### Desafio 3
Crie uma função em python que receba como input um determinado horário em horas e retorne a conversao deste horário para segundos

"""

##### ESCREVER A FUNCAO ABAIXO
def time_converter(t):
  ##### escrever abaixo
  segundos = t * 360
  
  return segundos

##### RODAR A FUNCAO
horas = float(input('Digite o valor das horas: '))
print(f'>>> {horas:.2f} hora(s) corresponde(m) a {time_converter(horas):.2f} segundos.')

"""### Desafio 4
Crie uma função em python que calcule a média artimética de uma aluna que cursou a disciplina de Programação I. A função deve receber como input as notas M1, M2 e M3 e calcular a média. Após a média calculada, a função deve anunciar se a aluna foi aprovado, reprovado ou pegou exame de acordo conm a seguinte classificação:

* Se a média estiver entre 0.0 e 4.0, o aluno está reprovado
* Se a média estiver entre 4.1 e 6.0, o aluno pegou exame
* Se a média for maior do que 6.0, o aluno está aprovado
* Se o aluno pegou exame, deve ser lida a nota do exame. Se a nota do exame for maior do que 6.0, está aprovado, senão; está reprovado

"""

##### ESCREVER A FUNCAO ABAIXO
def calcula_media(M1,M2,M3):
  ###### escrever abaixo
    media = (M1 + M2 + M3)/3                      #Cálculo da média 

    print(f'A média foi {media:.2f}')             #Mostra o valor da média calculada
  
    if 0.0 <= media <= 4.0:
      print('\033[1;31mAluna reprovada!\033[m')
    elif 4.1 <= media <= 6.0:
      print('\033[1;33mAluna pegou exame!\033[m')
      exame = float(input('Nota do exame: '))     #Se "4.1 <= média <= 6.0", informar a nota do exame
      if exame >= 6.0:
        print('\033[1;32mAluna aprovada!\033[m')
      else:
        print('\033[1;31mAluna reprovada!\033[m')
    else:
      print('\033[1;32mAluna aprovada!\033[m')

##### RODAR A FUNCAO
a = float(input('Valor da Nota 1: '))
b = float(input('Valor da Nota 2: '))
c = float(input('Valor da Nota 3: '))

calcula_media(a,b,c)

"""### Desafio 5
Dado a seguinte lista: 
* equipes_bootcamp_dados = [BerthaLutz, GraceHopper, JaquelineGoes, SarahGilbert]

1. Crie uma função em python que conte quantas vezes aparece a letra a em cada elemento da lista. Seu resultado deve ser uma lista . exemplo: [4,0,1,2]

2. Leia a lista de alunas: ['Maria', 'Ana','Camila','Mariana','Elaine','Patricia','Marina','Erica','Larissa','Luiza', 'Nicole','Bruna']

3. Crie uma função que atribua cada uma das alunas em uma das equipes da lista equipes_bootcamp_dados, de modo que cada equipe pode ter 3 alunas no máximo.

 Para isso ordene em alfabética. O seu resultado deve ser um dicionário python. exemplo {'BerthaLutz': ['Ana', 'Bruna', 'Camila'], 'GraceHopper': ['Elaine','Erika','Luiza'],... }

"""

##### ESCREVER A FUNCAO DA ETAPA 1
def contador(equipes_bootcamp_dados):
  #### escrever abaixo
    lista = []                #Criando a lista
    soma = 0
    for c in range(0,4):      #Como são 4 elementos na lista, temos "c" de 0 a 3
      for letra in equipes_bootcamp_dados[c]:
        if letra in 'Aa':     #Se o elemento tiver "a" ou "A", soma 1
          soma += 1
      lista.insert(c, soma)   #Inclui o valor da "soma" na posição "c"
      soma = 0                #Zera a contagem antes de passar para o próximo "c"

    print(lista)

###### RODAR A ETAPA 1
equipes_bootcamp_dados = ['BerthaLutz', 'GraceHopper', 'JaquelineGoes', 'SarahGilbert']
contador(equipes_bootcamp_dados)

##### LER A ETAPA 2
alunas = ['Maria', 'Ana','Camila','Mariana','Elaine','Patricia','Marina','Erica','Larissa','Luiza', 'Nicole','Bruna']
print(alunas)

##### ESCREVER A FUNCAO DA ETAPA 3
def ordenacao(lista_alunas, equipes_bootcamp_dados):
  ### escrever abaixo
  lista_alunas = alunas.copy()    #Criando uma cópia da lista "alunas"
  lista_alunas.sort()             #Colocando os elementos em ordem alfabética
  equipes = dict(zip(equipes_bootcamp_dados, lista_alunas))
  print(equipes)

for c in range(0, 3):
  print(lista_alunas[c], end=' ')

##### RODAR A FUNCAO DA ETAPA 3
ordenacao(lista_alunas, equipes_bootcamp_dados)

"""### Desafio 6
Escreva uma função em python que leia uma temperatura em graus Celsius e retorne a conversao dela em graus Fahrenheit. 

A fórmula de conversão é F = (9 * C + 160) / 5, na qual F é a temperatura em Fahrenheit e C é a temperatura em graus Celsius



"""

##### ESCREVER A FUNCAO
def conversor_temperatura(temperatura):
  ### escrever abaixo
  fahrenheit = (9 * temperatura + 160)/5      #Cálculo da conversão de Celsius para Fahrenheit

  return fahrenheit

##### RODAR A FUNCAO
celsius = float(input('Digite a temperatura em graus Celsius: '))
print(f'{celsius}°C equivale a {conversor_temperatura(celsius):.2f}°F')